### ISSUE TITLE
Install all at once?

### ISSUE THREAD

**Issue by Vistaus** [W-Floyd/solus-deepin#1]
Thank you so much for this! This is really cool and I really want to try it out (yes, I'm aware of the dragons and I don't mind)! But I don't really see a way to install all of the packages at once. Am I missing something or do I need to install the packages one by one? And if so, in what order?

Edit: I tried running sudo ./test_build.sh but it doesn't do anything.

**Comment by W-Floyd** [comment]
Hey, glad you're interested!

So I should really document my janky build setup better, but here goes:

The `install_list` file is a list of reasonable packages to install for the "full" Deepin setup (or, what I've got, anyway).
If you're just looking to build with no fuss, then try:
```
while read -r __package; do
./test_build.sh "${__package}"
done < 'install_list'
```
That will build all of the listed packages, along with all of their rundeps.
You'll want to do that under su probably, since it'll ask for permissions otherwise.
Once that's done, you can do `sudo ./test_install.sh --file` and it'll install everything (`sudo ./test_install.sh -u` would uninstall).

As you said, you're aware of the dragons lurking here. Big one right now would be that it'll uninstall GDM and replace it with LightDM if it needs to.

I'm happy to explain/fix things if you need anything!

**Comment by Vistaus** [comment]
@W-Floyd Thanks for your reply! :)

I executed the first command (the "while read -r [...]" one), but it fails :(

`root@solus /home/vistaus/Downloads/solus-deepin # while read -r __package; do ./test_build.sh "${__package}"; done < 'install_list'
rm: can't remove 'deepin-calculator/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'deepin-calendar/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'deepin-default-settings/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-qt-dbus-factory'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'deepin-qt-dbus-factory' failed, exiting.
rm: can't remove 'deepin-image-viewer/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'deepin-movie/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'deepin-music/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'deepin-picker/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-qt-dbus-factory'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'deepin-qt-dbus-factory' failed, exiting.
rm: can't remove 'deepin-screen-recorder/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-qt-dbus-factory'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'deepin-qt-dbus-factory' failed, exiting.
rm: can't remove 'deepin-screenshot/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-qt-dbus-factory'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'deepin-qt-dbus-factory' failed, exiting.
rm: can't remove 'deepin-system-monitor/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'deepin-terminal/*.eopkg': File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-qt-dbus-factory'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'  .  Stopped.
Building 'deepin-qt-dbus-factory' failed, exiting.
rm: can't remove 'deepin-voice-recorder/*.eopkg'  : File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'qt5-xcb-private-headers'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'. Stoped.
Building 'qt5-xcb-private-headers' failed, exiting.
rm: can't remove 'startdde/*.eopkg': File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-account-faces'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create  '../Makefile.common'. Stopped.
Building 'deepin-account-faces' failed, exiting.
rm: can't remove 'deepin-shortcut-viewer/*.eopkg': File or folder doesn't exist
Cleaning cache.
Cleaning cache.
Cleaning cache.
Building package 'deepin-qt-dbus-factory'
Makefile:1: ../Makefile.common: File or folder doesn't exist
make: *** There's no rule to create '../Makefile.common'. Stopped.
Building 'deepin-qt-dbus-factory' failed, exiting.
root@solus /home/vistaus/Downloads/solus-deepin # `

**Comment by W-Floyd** [comment]
Oof, yeah, my bad

Run `git clone https://dev.solus-project.com/source/common.git`, then:
```
ln -sv common/Makefile.common .
ln -sv common/Makefile.toplevel Makefile
ln -sv common/Makefile.iso .
```

Edit: I just pushed something so you shouldn't need to do that last block.

**Comment by W-Floyd** [comment]
Also, you might want to change the `./test_build.sh "${__package}"` to `./test_build.sh --no-delete "${__package}"`, otherwise it might rebuild some of the packages for no purpose (though it should be okay in this case)

**Comment by Vistaus** [comment]
Thank you so much! The build succeeded and everything's installed! However, I see no Deepin session. Note that I am using SDDM. Do I need to install LightDM for the session to show up?

**Comment by W-Floyd** [comment]
Hmm... I assume you've restarted?

~It will probably want LightDM though, as a guess.~
Maybe not, should be fine...

**Comment by Vistaus** [comment]
Yeah, it now works with LightDM. However, the settings don't really seem to work. Everything's huge (even though my screen is 1920x1080) and I can't change the size nor the fonts. Is that supposed to work or is that one of the current issues with Deepin on Solus?

**Comment by W-Floyd** [comment]
Hmm, it has been fine on my end. Can you screenshot?

**Comment by Vistaus** [comment]
Well, I managed to scale everything down now, however, I still can't change the font or font size. Also, upon logging in it keeps asking for my Wi-Fi password, it doesn't seem to remember it? And Vivaldi also wants me to relogin on every website after logging into the Deepin session. I knew it would be buggy, but I expected these basic things to work correctly :P

**Comment by W-Floyd** [comment]
Yeah, dunno. Scaling has been an issue for me before going the other way, that is, I have 4K and similar, and it doesn't always like to behave scaling up.

The password stuff sounds... interesting. Not sure I can help you there. I have been running it from a GNOME system with my packages installed on top, so there are probably some things inherited from that which it uses, but I don't realize.

**Comment by Vistaus** [comment]
For some reason, it did remember my Wi-Fi password this time so it's a bit buggy.

Also, the system language can't be changed through the control center and the keyboard layout isn't respected either. Are those features working for you?

**Comment by W-Floyd** [comment]
Hmm, I use US English, and it seemed to do that just fine for me. I can check that part though.

**Comment by Vistaus** [comment]
It's accidentally set to Dutch, but I want to use US English like I'm used to.

Also, the keyboard layout is respected but it's a bit buggy: after opening the lid of my laptop, it doesn't respect the layout, but after logging out and back in, it's respected again. Not sure what that's about.

**Comment by W-Floyd** [comment]
That's weird, I can't change my language to anything *except* US English.

The keyboard part, yeah, I could log out and in, and it remembered, can't test the laptop bit though.

**Comment by Vistaus** [comment]
It's also pretty strange that you can't manually force-set a language through dconf-editor. Almost all of Deepin's settings are exposed through dconf-editor, except the language screen settings. If I could just do that, the issue would be solved.

**Comment by Vistaus** [comment]
For some reason, the blur is gone after logging out and back in a few times and I can't set the blur effect anymore through control center (the switch won't turn on) :/ I should compile a list of issues for you :P

**Comment by W-Floyd** [comment]
For sure, just add it to the pile XD

Try Win+Shift+Tab maybe? That switches between their Metacity fork and their blur-enabled Mutter fork. Also, if you're in a VM (doesn't sound like it), it won't work properly either.

**Comment by Vistaus** [comment]
I'm not in a VM. I did something wrong, it's back now. I'll close this issue as this has long been solved now and I'll start a new one with all of the issues I encounter :P

**Comment by W-Floyd** [comment]
Yup... welcome to the thrilling world that is Deepin on Solus :stuck_out_tongue_closed_eyes:

**Comment by Vistaus** [comment]
Haha :D

**Comment by W-Floyd** [comment]
Sounds good, opening issues. Mind you, I'm going to have less time to put into this in future, I'll be starting into University middle of next month, but... we'll see. It's still just a fun hobby project, at this point.

**Comment by Vistaus** [comment]
I'll just report everything I come across and if you can fix the issues, that'd be nice, but if you can't, then that's okay too. University is more important than fixing issues in a hobby project :)

**Comment by Vistaus** [comment]
Hmm, installing doesn't work anymore. I spent the last hour or so building everything with

while read -r __package; do
./test_build.sh --no-delete "${__package}"
done < 'install_list'

and now it says that the packages don't exist :/ Never had this before, last time I used your packages, it installed fine. All of the packages are built and available in the subsequent subdirectories as eopkg files.

```
vistaus@solus ~/Apps/from=git/solus-deepin $ sudo ./test_install.sh --file
Password: 
Package dtkcore does not exist. Cannot remove.
Package blur-effect does not exist. Cannot remove.
Package deepin-sound-theme does not exist. Cannot remove.
Package deepin-system-monitor does not exist. Cannot remove.
Package deepin-polkit-agent does not exist. Cannot remove.
Package geoip does not exist. Cannot remove.
Package perl-config-tiny does not exist. Cannot remove.
Package deepin-control-center does not exist. Cannot remove.
Package deepin-notifications does not exist. Cannot remove.
Package deepin-calculator does not exist. Cannot remove.
Package libmongoc does not exist. Cannot remove.
Package deepin-desktop-schemas does not exist. Cannot remove.
Package deepin-clutter-gtk does not exist. Cannot remove.
Package deepin-cogl does not exist. Cannot remove.
Package deepin-account-faces does not exist. Cannot remove.
Package deepin-metacity does not exist. Cannot remove.
Package deepin-file-manager does not exist. Cannot remove.
Package deepin-voice-recorder does not exist. Cannot remove.
Package deepin-screenshot does not exist. Cannot remove.
Package deepin-wm-switcher does not exist. Cannot remove.
Package deepin-terminal does not exist. Cannot remove.
Package proxychains-ng does not exist. Cannot remove.
Package gsettings-qt does not exist. Cannot remove.
Package deepin-icon-theme does not exist. Cannot remove.
Package deepin-qt-dbus-factory does not exist. Cannot remove.
Package deepin-calendar does not exist. Cannot remove.
Package dtkwm does not exist. Cannot remove.
Package deepin-screen-recorder does not exist. Cannot remove.
Package deepin-picker does not exist. Cannot remove.
Package libqtxdg does not exist. Cannot remove.
Package treefrog-framework does not exist. Cannot remove.
Package deepin-gtk-theme does not exist. Cannot remove.
Package deepin-clutter does not exist. Cannot remove.
Package deepin-shortcut-viewer does not exist. Cannot remove.
Package dtkwidget does not exist. Cannot remove.
Package deepin-menu does not exist. Cannot remove.
Package deepin-network-utils does not exist. Cannot remove.
Package startdde does not exist. Cannot remove.
Package deepin-default-settings does not exist. Cannot remove.
Package deepin-desktop does not exist. Cannot remove.
Package deepin-daemon does not exist. Cannot remove.
Package deepin-wm does not exist. Cannot remove.
Package deepin-api does not exist. Cannot remove.
Package deepin-qt5integration does not exist. Cannot remove.
Package deepin-wallpapers does not exist. Cannot remove.
Package deepin-introduction does not exist. Cannot remove.
Package deepin-desktop-base does not exist. Cannot remove.
Package deepin-image-viewer does not exist. Cannot remove.
Package deepin-dock does not exist. Cannot remove.
Package deepin-movie does not exist. Cannot remove.
Package deepin-mutter does not exist. Cannot remove.
Package deepin-launcher does not exist. Cannot remove.
Package deepin-anything does not exist. Cannot remove.
Package deepin-music does not exist. Cannot remove.
Package deepin-qt5dxcb-plugin does not exist. Cannot remove.
Package deepin-gettext-tools does not exist. Cannot remove.
Package avfs does not exist. Cannot remove.
Package xcur2png does not exist. Cannot remove.
Package deepin-session-ui does not exist. Cannot remove.
Package liblightdm-qt5 does not exist. Cannot remove.
No packages to remove.
deepin-calculator deepin-calendar deepin-default-settings deepin-image-viewer deepin-movie deepin-music deepin-picker deepin-screen-recorder deepin-screenshot deepin-system-monitor deepin-terminal deepin-voice-recorder startdde deepin-shortcut-viewer
deepin-image-viewer is missing
vistaus@solus ~/Apps/from=git/solus-deepin $ 
```

What's wrong?

**Comment by W-Floyd** [comment]
Deepin-image-viewer is currently failing to build it seems. Temporary
solution is to remove it from the `install_list`

**Comment by Vistaus** [comment]
That seems to make it work, thanks :)

**Comment by Vistaus** [comment]
Btw, is there any way to update only the updated packages? Up till now, I just re-cloned the repo every time, but as a result, it starts building everything from scratch. So is there any way to update only what's actually updated?

**Comment by W-Floyd** [comment]
Yeah, I'll look into it for you, but it shouldn't take much. I tend to push
things only that need to be rebuilt. It's in a state of flux right now,
I'll tell you when you're good to go.

**Comment by Vistaus** [comment]
Cool, thanks :)
