### ISSUE TITLE
im a noob :(

### ISSUE THREAD

**Issue by ghost** [W-Floyd/solus-deepin#9]
hey man i realy need deepin-movie
how do i build this package ?

**Comment by W-Floyd** [comment]
I shall assume you know a little about how to package for Solus. If not, [read this](https://getsol.us/articles/packaging/) and become comfortable before undertaking this. My build scripts are currently broken (and so I removed them), and I haven't tried building any of this in ages, but if you want, you can try building all the packages for it indivindually, and copy them to your local repo as needed. To determine which packages you need, you'll need to walk through the builddeps and rundeps of each package starting with `deepin-movie`. For example, you lines you need to look at are:

```
builddeps  :
    - pkgconfig(dtkwidget)
[...etc]
    - pkgconfig(xtst)
rundeps    :
    - deepin-qt5integration
```

My scripts would ordinarily compare against the [pkgconfig dictionary](https://github.com/W-Floyd/solus-deepin/blob/master/pkgconfig_dictionary.yml) I have set up, and walk back from there. Eg:

```
  - name      : dtkwidget-devel
    pkgconfigs:
        - dtkwidget
```

Tells us that the package that provides `pkgconfig(dtkwidget)` is `dtkwidget-devel`, and hence `dtkwidget`. So you can use that to find the package names outright, and continue until you find the packages that have no unsatisfied builddeps. Past that, sorry, you're on your own...

**Comment by ghost** [comment]
i get this error

```
make build
make[1]: Entering directory '/home/fatih/solus-deepin/deepin-movie'
sudo solbuild build package.yml -p unstable-x86_64; 
Profile is not installed: Did you forget to init?
make[1]: Leaving directory '/home/fatih/solus-deepin/deepin-movie'
make abireport
make[1]: Entering directory '/home/fatih/solus-deepin/deepin-movie'
abireport -p abi_ -D `dirname package.yml` scan-packages `dirname package.yml`
error locating packages: No packages in directory .
make[1]: *** [../Makefile.common:15: abireport] Error 1
make[1]: Leaving directory '/home/fatih/solus-deepin/deepin-movie'
make: *** [../Makefile.common:12: complete] Error 2
```

**Comment by W-Floyd** [comment]
You need to follow the instructions from the help centre. The
`unstable-x86_64` profile is not installed.

**Comment by ghost** [comment]
almost there 
now i get 

```bash
[BuildDep] Checking build-deps for deepin-movie-3.2.17-24
[pkgconfig:dtkwidget] This dependency is not in any repo
[BuildDep] pkgconfig(dtkwidget) build dep does not exist in the repository.
ERRO[08:22:43] Failed to install build dependencies          buildFile="/home/build/work/package.yml" error="exit status 1"
ERRO[08:22:46] Failed to build packages                     
make[1]: Leaving directory '/home/fatih/solus-deepin/deepin-movie'
make abireport
make[1]: Entering directory '/home/fatih/solus-deepin/deepin-movie'
abireport -p abi_ -D `dirname package.yml` scan-packages `dirname package.yml`
error locating packages: No packages in directory .
make[1]: *** [../Makefile.common:15: abireport] Error 1
make[1]: Leaving directory '/home/fatih/solus-deepin/deepin-movie'
make: *** [../Makefile.common:12: complete] Error 2
```

**Comment by ghost** [comment]
i made it
